- name: Configurando os templates das vms Mininet.
  blockinfile:
    path: "/tmp/{{ item.name }}.xml"
    block: |
        <domain type='kvm'>
          <os>
            <type>hvm</type>
            <boot dev='hd'/>
          </os>
          <features>
            <acpi/>
            <apic/>
            <pae/>
          </features>
          <devices>
            <interface type='network'>
              <mac address='{{ item.mac1 }}'/>
              <source network='{{ item.int1 }}'/>
              <model type='virtio'/>
            </interface>
            <interface type='network'>
              <mac address='{{ item.mac2 }}'/>
              <source network='{{ item.int2 }}'/>
              <model type='virtio'/>
            </interface>
            <interface type='network'>
              <mac address='{{ item.mac3 }}'/>
              <source network='{{ item.int3 }}'/>
              <model type='virtio'/>
            </interface>
            <interface type='network'>
              <mac address='{{ item.mac4 }}'/>
              <source network='{{ item.int4 }}'/>
              <model type='virtio'/>
            </interface>
            <interface type='network'>
              <mac address='{{ item.mac5 }}'/>
              <source network='{{ item.int5 }}'/>
              <model type='virtio'/>
            </interface>
            <serial type='pty'>
              <source path='/dev/pts/3'/>
              <target port='0'/>
            </serial>
            <graphics type='vnc' autoport='yes' listen='127.0.0.1'>
              <listen type='address' address='127.0.0.1'/>
            </graphics>
            <graphics type='spice' autoport='yes' listen='127.0.0.1'>
              <listen type='address' address='127.0.0.1'/>
            </graphics>
            <video>
              <model type='qxl'/>
            </video>
            <channel type='unix'>
              <target type='virtio' name='org.qemu.guest_agent.0'/>
            </channel>
          </devices>
        </domain>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    create: True
  loop: "{{ vms_mininet }}"

- name: Copiando arquivos das configurações de rede das vms Mininet.
  ansible.builtin.copy:
    src: "files/{{ item.name }}.cfg"
    dest: "/tmp"
  loop: "{{ vms_mininet }}"

- name: Criando as VMs.
  ansible.builtin.shell: /usr/bin/uvt-kvm create "{{ item.name }}" --memory "{{ item.memory }}" --cpu "{{ item.cpu }}" --disk "{{ item.disk }}" --template /tmp/{{ item.name }}.xml --user-data "/tmp/{{ item.name }}.cfg" #--no-start
  loop: "{{ vms_mininet }}"