- name: Configurando os arquivos /tmp/{{ item.name }}.xml das redes do tipo NAT.
  blockinfile:
    path: "/tmp/{{ item.name }}.xml"
    block: |
        <network>
          <name>{{ item.name }}</name>
          <forward mode="nat">
            <nat>
              <port start="1024" end="65535"/>
            </nat>
          </forward>
          <bridge name="{{ item.bridge }}" stp="on" delay="0"/>
          <ip address="{{ item.ip }}" netmask="{{ item.mask }}">
            <dhcp>
              <range start="{{ item.range_start }}" end="{{ item.range_end }}"/>
            </dhcp>
          </ip>
        </network>
    create: True
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  loop: "{{ network_nat }}"

- name: Configurando os arquivos /tmp/{{ item.name }}.xml das redes do tipo ISOLADAS.
  blockinfile:
    path: "/tmp/{{ item.name }}.xml"
    block: |
        <network>
          <name>{{ item.name }}</name>
          <domain name="{{ item.name }}"/>
          <bridge name="{{ item.bridge }}" stp="on" delay="0"/>
        </network>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    create: True
  loop: "{{ network }}"

- name: Criando as redes do tipo NAT no KVM.
  ansible.builtin.shell: /usr/bin/virsh net-define --file /tmp/{{ item.name }}.xml --validate
  loop: "{{ network_nat }}"
  ignore_errors: yes

- name: Criando as redes do tipo ISOLADAS no KVM
  ansible.builtin.shell: /usr/bin/virsh net-define --file /tmp/{{ item.name }}.xml --validate
  loop: "{{ network }}"
  ignore_errors: yes
  
- name: Iniciando as redes do tipo NAT no KVM.
  ansible.builtin.shell: /usr/bin/virsh net-start {{ item.name }}
  loop: "{{ network_nat }}"
  ignore_errors: yes

- name: Iniciando as redes do tipo ISOLADAS no KVM.
  ansible.builtin.shell: /usr/bin/virsh net-start {{ item.name }}
  loop: "{{ network }}"
  ignore_errors: yes

- name: Habilitando as redes do tipo NAT na inicialização KVM.
  ansible.builtin.shell: /usr/bin/virsh net-autostart {{ item.name }}
  loop: "{{ network_nat }}"
  ignore_errors: yes

- name: Habilitando as redes do tipo ISOLADAS na inicialização KVM.
  ansible.builtin.shell: /usr/bin/virsh net-autostart {{ item.name }}
  loop: "{{ network }}"
  ignore_errors: yes
