---
- name: Playbook Infraestrutura
  hosts: all
  remote_user: administrador
  become: true
  gather_facts: no

  tasks:

    - ansible.builtin.import_role:
        name: KVM
      when: inventory_hostname in groups['KVM']

    - name: Pausa por 2 minutos para as VMS subirem.
      ansible.builtin.pause:
        minutes: 2    
     
    - ansible.builtin.import_role:
        name: Mininet
      when: inventory_hostname in groups['Mininet']
    
    - ansible.builtin.import_role:
        name: Free5GC
      when: inventory_hostname in groups['Free5GC']

    - ansible.builtin.import_role:
        name: UERANSIM
      when: inventory_hostname in groups['UERANSIM']
