---
- name: Roles Playbook
  hosts: all
  remote_user: administrador
  become: true
  gather_facts: no

  tasks:

    - name: Playbook Infraestrutura
      import_playbook: playbook_infraestrutura.yaml

    - name: Playbook 5G
      import_playbook: playbook_5g.yaml